import type { Product } from "@/lib/types";

const now = "2026-01-01T00:00:00.000Z";

function demoProduct(product: Omit<Product, "active" | "featured" | "is_demo" | "created_at" | "updated_at"> & Partial<Pick<Product, "featured">>): Product {
  return {
    ...product,
    active: true,
    featured: product.featured ?? false,
    is_demo: true,
    created_at: now,
    updated_at: now
  };
}

export const demoProducts: Product[] = [
  demoProduct({
    id: "prod_interior_plus",
    name: "[DEMO] Demo Interior Plus",
    sku: "DEMO-INT-PLUS",
    category: "Son noi that",
    description: "Demo interior wall paint for living rooms, bedrooms and apartments.",
    interior_or_exterior: "interior",
    main_benefits: ["Smooth finish", "Easy cleaning", "Low odor"],
    suitable_surfaces: ["Interior cement wall", "Interior skim coat"],
    suitable_projects: ["Living room repaint", "Bedroom repaint", "Apartment"],
    coverage: "10-12 m2/liter/coat depending on surface",
    coverage_value: 11,
    coats: 2,
    available_sizes: ["1L", "5L", "18L"],
    price: null,
    price_unit: null,
    discount: null,
    warranty: null,
    technical_info: { Type: "Demo interior topcoat" },
    application_instructions: "Apply on a clean, dry surface. Primer is recommended before topcoat.",
    drying_time: null,
    color_info: "Demo color data only. Replace with the company's real color information.",
    features: ["Smooth finish", "Easy cleaning", "Low odor"],
    suitable_for: ["Living room", "Bedroom", "Apartment"],
    faq: {
      "Is primer needed?": "Primer is recommended so the topcoat bonds evenly and lasts longer."
    },
    sort_order: 10,
    featured: true
  }),
  demoProduct({
    id: "prod_exterior_shield",
    name: "[DEMO] Demo Exterior Shield",
    sku: "DEMO-EXT-SHIELD",
    category: "Son ngoai that",
    description: "Demo exterior paint for facades and outdoor walls.",
    interior_or_exterior: "exterior",
    main_benefits: ["Weather resistant", "Mold resistant", "Durable color"],
    suitable_surfaces: ["Exterior cement wall", "Facade"],
    suitable_projects: ["Facade", "Outdoor wall", "Balcony"],
    coverage: "9-11 m2/liter/coat depending on surface",
    coverage_value: 10,
    coats: 2,
    available_sizes: ["5L", "18L"],
    price: null,
    price_unit: null,
    discount: null,
    warranty: null,
    technical_info: { Type: "Demo exterior topcoat" },
    application_instructions: "Apply in dry weather and avoid rain during the first drying period.",
    drying_time: null,
    color_info: "Demo color data only. Replace with the company's real color information.",
    features: ["Weather resistant", "Mold resistant", "Durable color"],
    suitable_for: ["Facade", "Outdoor wall", "Balcony"],
    faq: {},
    sort_order: 20,
    featured: true
  }),
  demoProduct({
    id: "prod_primer",
    name: "[DEMO] Demo Primer Pro",
    sku: "DEMO-PRI-PRO",
    category: "Son lot",
    description: "Demo alkaline-resistant primer that improves adhesion before topcoat.",
    interior_or_exterior: "both",
    main_benefits: ["Alkali resistant", "Improves adhesion", "Helps topcoat color look even"],
    suitable_surfaces: ["New wall", "Skim-coated wall"],
    suitable_projects: ["New house", "Repaint after surface treatment"],
    coverage: "11-13 m2/liter/coat depending on surface",
    coverage_value: 12,
    coats: 1,
    available_sizes: ["5L", "18L"],
    price: null,
    price_unit: null,
    discount: null,
    warranty: null,
    technical_info: { Type: "Demo primer" },
    application_instructions: "Apply one primer coat before topcoat.",
    drying_time: null,
    color_info: "Demo color data only.",
    features: ["Alkali resistant", "Improves adhesion", "Even topcoat color"],
    suitable_for: ["New house", "Prepared wall"],
    faq: {},
    sort_order: 30
  }),
  demoProduct({
    id: "prod_waterproof",
    name: "[DEMO] Demo Waterproof Guard",
    sku: "DEMO-WP-GUARD",
    category: "Son chong tham",
    description: "Demo waterproofing material for areas with water exposure.",
    interior_or_exterior: "specialty",
    main_benefits: ["Waterproofing", "Good adhesion", "For cementitious surfaces"],
    suitable_surfaces: ["Cement", "Concrete"],
    suitable_projects: ["Roof terrace", "Bathroom", "Damp wall"],
    coverage: "Depends on surface condition and application system",
    coverage_value: null,
    coats: null,
    available_sizes: ["5kg", "20kg"],
    price: null,
    price_unit: null,
    discount: null,
    warranty: null,
    technical_info: { Type: "Demo waterproofing" },
    application_instructions: "Surface inspection is required before selecting the application system.",
    drying_time: null,
    color_info: "Demo color data only.",
    features: ["Waterproofing", "Good adhesion", "For cementitious surfaces"],
    suitable_for: ["Roof terrace", "Bathroom", "Damp wall"],
    faq: {},
    sort_order: 40
  })
];
